"""followers

Revision ID: 033ff50a6ec6
Revises: 2d1708ef95af
Create Date: 2021-02-23 05:10:36.637663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033ff50a6ec6'
down_revision = '2d1708ef95af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
